// wikiSlug: título exato do artigo na Wikipedia PT
export const PARKS = [
  { id: 1, name: "Serra da Bocaina", state: "SP/RJ", dist: 209, access: "🚗", status: "aberto", slug: "Parque_Nacional_da_Serra_da_Bocaina" },
  { id: 2, name: "Itatiaia", state: "MG/RJ", dist: 240, access: "🚗", status: "aberto", slug: "Parque_Nacional_do_Itatiaia" },
  { id: 3, name: "Superagui", state: "PR", dist: 251, access: "⛵", status: "aberto", slug: "Parque_Nacional_do_Superagui" },
  { id: 4, name: "Marinho das Ilhas dos Currais", state: "PR", dist: 300, access: "⛵", status: "aberto", slug: "Parque_Nacional_Marinho_das_Ilhas_dos_Currais" },
  { id: 5, name: "Saint-Hilaire/Lange", state: "PR", dist: 312, access: "🚗", status: "limitado", slug: "Parque_Nacional_de_Saint-Hilaire/Lange" },
  { id: 6, name: "Guaricana", state: "PR", dist: 335, access: "🚗", status: "limitado", slug: "Parque_Nacional_Guaricana" },
  { id: 7, name: "Tijuca", state: "RJ", dist: 352, access: "🚗", status: "aberto", slug: "Parque_Nacional_da_Tijuca" },
  { id: 8, name: "Serra da Canastra", state: "MG", dist: 356, access: "🚗", status: "aberto", slug: "Parque_Nacional_da_Serra_da_Canastra" },
  { id: 9, name: "Campos Gerais", state: "PR", dist: 376, access: "🚗", status: "aberto", slug: "Parque_Nacional_dos_Campos_Gerais" },
  { id: 10, name: "Serra dos Órgãos", state: "RJ", dist: 383, access: "🚗", status: "aberto", slug: "Parque_Nacional_da_Serra_dos_Órgãos" },
  { id: 11, name: "Serra do Itajaí", state: "SC", dist: 470, access: "🚗", status: "limitado", slug: "Parque_Nacional_da_Serra_do_Itajaí" },
  { id: 12, name: "Serra do Gandarela", state: "MG", dist: 490, access: "🚗", status: "limitado", slug: "Parque_Nacional_da_Serra_do_Gandarela" },
  { id: 13, name: "Restinga de Jurubatiba", state: "RJ", dist: 548, access: "🚗", status: "limitado", slug: "Parque_Nacional_da_Restinga_de_Jurubatiba" },
  { id: 14, name: "Serra do Cipó", state: "MG", dist: 565, access: "🚗", status: "aberto", slug: "Parque_Nacional_da_Serra_do_Cipó" },
  { id: 15, name: "São Joaquim", state: "SC", dist: 584, access: "🚗", status: "aberto", slug: "Parque_Nacional_de_São_Joaquim" },
  { id: 16, name: "Caparaó", state: "ES/MG", dist: 608, access: "🚗", status: "aberto", slug: "Parque_Nacional_de_Caparaó" },
  { id: 17, name: "Araucárias", state: "SC", dist: 645, access: "🚗", status: "limitado", slug: "Parque_Nacional_das_Araucárias" },
  { id: 18, name: "Sempre-vivas", state: "MG", dist: 703, access: "🚗", status: "limitado", slug: "Parque_Nacional_das_Sempre-Vivas" },
  { id: 19, name: "Serra Geral", state: "RS/SC", dist: 705, access: "🚗", status: "aberto", slug: "Parque_Nacional_da_Serra_Geral" },
  { id: 20, name: "Aparados da Serra", state: "RS/SC", dist: 716, access: "🚗", status: "aberto", slug: "Parque_Nacional_de_Aparados_da_Serra" },
  { id: 21, name: "Ilha Grande", state: "MS/PR", dist: 752, access: "🚗", status: "limitado", slug: "Parque_Nacional_de_Ilha_Grande" },
  { id: 22, name: "Iguaçu", state: "PR", dist: 777, access: "🚗", status: "aberto", slug: "Parque_Nacional_do_Iguaçu" },
  { id: 23, name: "Emas", state: "GO", dist: 891, access: "🚗", status: "aberto", slug: "Parque_Nacional_das_Emas" },
  { id: 24, name: "Brasília", state: "DF", dist: 891, access: "🚗", status: "aberto", slug: "Parque_Nacional_de_Brasília" },
  { id: 25, name: "Grande Sertão Veredas", state: "MG/BA", dist: 944, access: "🚗", status: "limitado", slug: "Parque_Nacional_Grande_Sertão_Veredas" },
  { id: 26, name: "Lagoa do Peixe", state: "RS", dist: 946, access: "🚗", status: "limitado", slug: "Parque_Nacional_da_Lagoa_do_Peixe" },
  { id: 27, name: "Cavernas do Peruaçu", state: "MG", dist: 972, access: "🚗", status: "aberto", slug: "Parque_Nacional_Cavernas_do_Peruaçu" },
  { id: 28, name: "Marinho dos Abrolhos", state: "BA", dist: 1032, access: "⛵", status: "aberto", slug: "Parque_Nacional_Marinho_dos_Abrolhos" },
  { id: 29, name: "Descobrimento", state: "BA", dist: 1050, access: "🚗", status: "limitado", slug: "Parque_Nacional_do_Descobrimento" },
  { id: 30, name: "Alto Cariri", state: "BA", dist: 1058, access: "🚗", status: "limitado", slug: "Parque_Nacional_do_Alto_Cariri" },
  { id: 31, name: "Monte Pascoal", state: "BA", dist: 1060, access: "🚗", status: "limitado", slug: "Parque_Nacional_e_Histórico_do_Monte_Pascoal" },
  { id: 32, name: "Chapada dos Veadeiros", state: "GO", dist: 1060, access: "🚗", status: "aberto", slug: "Parque_Nacional_da_Chapada_dos_Veadeiros" },
  { id: 33, name: "Serra da Bodoquena", state: "MS", dist: 1066, access: "🚗", status: "aberto", slug: "Parque_Nacional_da_Serra_da_Bodoquena" },
  { id: 34, name: "Pau Brasil", state: "BA", dist: 1097, access: "🚗", status: "limitado", slug: "Parque_Nacional_do_Pau-Brasil" },
  { id: 35, name: "Serra das Lontras", state: "BA", dist: 1205, access: "🚗", status: "limitado", slug: "Parque_Nacional_da_Serra_das_Lontras" },
  { id: 36, name: "Boa Nova", state: "BA", dist: 1226, access: "🚗", status: "limitado", slug: "Parque_Nacional_de_Boa_Nova" },
  { id: 37, name: "Pantanal Matogrossense", state: "MT", dist: 1302, access: "🚗⛵", status: "limitado", slug: "Parque_Nacional_do_Pantanal_Matogrossense" },
  { id: 38, name: "Chapada Diamantina", state: "BA", dist: 1310, access: "🚗", status: "aberto", slug: "Parque_Nacional_da_Chapada_Diamantina" },
  { id: 39, name: "Chapada dos Guimarães", state: "MT", dist: 1332, access: "🚗", status: "aberto", slug: "Parque_Nacional_da_Chapada_dos_Guimarães" },
  { id: 40, name: "Araguaia", state: "TO", dist: 1496, access: "🚗", status: "fechado", slug: "Parque_Nacional_do_Araguaia" },
  { id: 41, name: "Nascentes do Rio Parnaíba", state: "BA/MA/PI/TO", dist: 1505, access: "🚗", status: "limitado", slug: "Parque_Nacional_das_Nascentes_do_Rio_Parnaíba" },
  { id: 42, name: "Boqueirão da Onça", state: "BA", dist: 1584, access: "🚗", status: "limitado", slug: "Parque_Nacional_do_Boqueirão_da_Onça" },
  { id: 43, name: "Serra das Confusões", state: "PI", dist: 1632, access: "🚗", status: "limitado", slug: "Parque_Nacional_da_Serra_das_Confusões" },
  { id: 44, name: "Serra de Itabaiana", state: "SE", dist: 1732, access: "🚗", status: "aberto", slug: "Parque_Nacional_Serra_de_Itabaiana" },
  { id: 45, name: "Serra da Capivara", state: "PI", dist: 1744, access: "🚗", status: "aberto", slug: "Parque_Nacional_Serra_da_Capivara" },
  { id: 46, name: "Chapada das Mesas", state: "MA", dist: 1816, access: "🚗", status: "aberto", slug: "Parque_Nacional_da_Chapada_das_Mesas" },
  { id: 47, name: "Catimbau", state: "PE", dist: 1942, access: "🚗", status: "aberto", slug: "Parque_Nacional_do_Catimbau" },
  { id: 48, name: "Campos Ferruginosos", state: "PA", dist: 1947, access: "🚗", status: "limitado", slug: "Parque_Nacional_dos_Campos_Ferruginosos" },
  { id: 49, name: "Rio Novo", state: "PA", dist: 2037, access: "🚗⛵", status: "limitado", slug: "Parque_Nacional_do_Rio_Novo" },
  { id: 50, name: "Serra do Pardo", state: "PA", dist: 2122, access: "🚗⛵", status: "limitado", slug: "Parque_Nacional_da_Serra_do_Pardo" },
  { id: 51, name: "Juruena", state: "AM/MT", dist: 2204, access: "🚗⛵", status: "limitado", slug: "Parque_Nacional_do_Juruena" },
  { id: 52, name: "Jamanxim", state: "PA", dist: 2206, access: "🚗", status: "limitado", slug: "Parque_Nacional_do_Jamanxim" },
  { id: 53, name: "Sete Cidades", state: "PI", dist: 2226, access: "🚗", status: "aberto", slug: "Parque_Nacional_de_Sete_Cidades" },
  { id: 54, name: "Pacaás Novos", state: "RO", dist: 2243, access: "🚗", status: "limitado", slug: "Parque_Nacional_de_Pacaás_Novos" },
  { id: 55, name: "Furna Feia", state: "RN", dist: 2277, access: "🚗", status: "aberto", slug: "Parque_Nacional_da_Furna_Feia" },
  { id: 56, name: "Ubajara", state: "CE", dist: 2288, access: "🚗", status: "aberto", slug: "Parque_Nacional_de_Ubajara" },
  { id: 57, name: "Serra da Cutia", state: "RO", dist: 2290, access: "🚗⛵", status: "limitado", slug: "Parque_Nacional_da_Serra_da_Cutia" },
  { id: 58, name: "Campos Amazônicos", state: "AM/RO", dist: 2322, access: "🚗⛵", status: "limitado", slug: "Parque_Nacional_dos_Campos_Amazônicos" },
  { id: 59, name: "Acari", state: "AM", dist: 2357, access: "⛵", status: "limitado", slug: "Parque_Nacional_do_Acari" },
  { id: 60, name: "Amazônia", state: "PA", dist: 2396, access: "🚗⛵", status: "aberto", slug: "Parque_Nacional_da_Amazônia" },
  { id: 61, name: "Jericoacoara", state: "CE", dist: 2402, access: "🚗", status: "aberto", slug: "Parque_Nacional_de_Jericoacoara" },
  { id: 62, name: "Lençóis Maranhenses", state: "MA", dist: 2421, access: "🚗", status: "aberto", slug: "Parque_Nacional_dos_Lençóis_Maranhenses" },
  { id: 63, name: "Mapinguari", state: "AM/RO", dist: 2522, access: "✈️⛵", status: "limitado", slug: "Parque_Nacional_Mapinguari" },
  { id: 64, name: "Nascentes do Lago Jari", state: "AM", dist: 2595, access: "✈️⛵", status: "limitado", slug: "Parque_Nacional_das_Nascentes_do_Lago_Jari" },
  { id: 65, name: "Marinho de Fernando de Noronha", state: "PE", dist: 2669, access: "✈️", status: "aberto", slug: "Parque_Nacional_Marinho_de_Fernando_de_Noronha" },
  { id: 66, name: "Anavilhanas", state: "AM", dist: 2810, access: "⛵", status: "aberto", slug: "Parque_Nacional_de_Anavilhanas" },
  { id: 67, name: "Jaú", state: "AM", dist: 2813, access: "⛵", status: "limitado", slug: "Parque_Nacional_do_Jaú" },
  { id: 68, name: "Montanhas do Tumucumaque", state: "AP", dist: 2906, access: "✈️⛵", status: "limitado", slug: "Parque_Nacional_Montanhas_do_Tumucumaque" },
  { id: 69, name: "Cabo Orange", state: "AP", dist: 3056, access: "🚗⛵", status: "limitado", slug: "Parque_Nacional_do_Cabo_Orange" },
  { id: 70, name: "Viruá", state: "RR", dist: 3176, access: "🚗", status: "limitado", slug: "Parque_Nacional_do_Viruá" },
  { id: 71, name: "Serra da Mocidade", state: "RR", dist: 3204, access: "✈️⛵", status: "limitado", slug: "Parque_Nacional_da_Serra_da_Mocidade" },
  { id: 72, name: "Serra do Divisor", state: "AC", dist: 3347, access: "🚗⛵", status: "limitado", slug: "Parque_Nacional_da_Serra_do_Divisor" },
  { id: 73, name: "Pico da Neblina", state: "AM", dist: 3423, access: "✈️⛵", status: "fechado", slug: "Parque_Nacional_do_Pico_da_Neblina" },
  { id: 74, name: "Monte Roraima", state: "RR", dist: 3528, access: "🚗🥾", status: "aberto", slug: "Parque_Nacional_do_Monte_Roraima" },
];
