// wikiSlug: título exato do artigo na Wikipedia PT
export const PARKS = [
  { id: 1, name: "Serra da Bocaina", state: "SP/RJ", dist: 209, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_da_Serra_da_Bocaina" },
  { id: 2, name: "Itatiaia", state: "MG/RJ", dist: 240, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_do_Itatiaia" },
  { id: 3, name: "Superagui", state: "PR", dist: 251, access: "\u26F5", status: "aberto", slug: "Parque_Nacional_do_Superagui" },
  { id: 4, name: "Marinho das Ilhas dos Currais", state: "PR", dist: 300, access: "\u26F5", status: "aberto", slug: "Parque_Nacional_Marinho_das_Ilhas_dos_Currais" },
  { id: 5, name: "Saint-Hilaire/Lange", state: "PR", dist: 312, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_de_Saint-Hilaire/Lange" },
  { id: 6, name: "Guaricana", state: "PR", dist: 335, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_Guaricana" },
  { id: 7, name: "Tijuca", state: "RJ", dist: 352, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_da_Tijuca" },
  { id: 8, name: "Serra da Canastra", state: "MG", dist: 356, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_da_Serra_da_Canastra" },
  { id: 9, name: "Campos Gerais", state: "PR", dist: 376, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_dos_Campos_Gerais" },
  { id: 10, name: "Serra dos \u00D3rg\u00E3os", state: "RJ", dist: 383, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_da_Serra_dos_\u00D3rg\u00E3os" },
  { id: 11, name: "Serra do Itaja\u00ED", state: "SC", dist: 470, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_da_Serra_do_Itaja\u00ED" },
  { id: 12, name: "Serra do Gandarela", state: "MG", dist: 490, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_da_Serra_do_Gandarela" },
  { id: 13, name: "Restinga de Jurubatiba", state: "RJ", dist: 548, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_da_Restinga_de_Jurubatiba" },
  { id: 14, name: "Serra do Cip\u00F3", state: "MG", dist: 565, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_da_Serra_do_Cip\u00F3" },
  { id: 15, name: "S\u00E3o Joaquim", state: "SC", dist: 584, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_de_S\u00E3o_Joaquim" },
  { id: 16, name: "Capara\u00F3", state: "ES/MG", dist: 608, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_do_Capara\u00F3" },
  { id: 17, name: "Arauc\u00E1rias", state: "SC", dist: 645, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_das_Arauc\u00E1rias" },
  { id: 18, name: "Sempre-vivas", state: "MG", dist: 703, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_das_Sempre-Vivas" },
  { id: 19, name: "Serra Geral", state: "RS/SC", dist: 705, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_da_Serra_Geral" },
  { id: 20, name: "Aparados da Serra", state: "RS/SC", dist: 716, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_de_Aparados_da_Serra" },
  { id: 21, name: "Ilha Grande", state: "MS/PR", dist: 752, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_de_Ilha_Grande" },
  { id: 22, name: "Igua\u00E7u", state: "PR", dist: 777, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_do_Igua\u00E7u" },
  { id: 23, name: "Emas", state: "GO", dist: 891, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_das_Emas" },
  { id: 24, name: "Bras\u00EDlia", state: "DF", dist: 891, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_de_Bras\u00EDlia" },
  { id: 25, name: "Grande Sert\u00E3o Veredas", state: "MG/BA", dist: 944, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_Grande_Sert\u00E3o_Veredas" },
  { id: 26, name: "Lagoa do Peixe", state: "RS", dist: 946, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_da_Lagoa_do_Peixe" },
  { id: 27, name: "Cavernas do Perua\u00E7u", state: "MG", dist: 972, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_Cavernas_do_Perua\u00E7u" },
  { id: 28, name: "Marinho dos Abrolhos", state: "BA", dist: 1032, access: "\u26F5", status: "aberto", slug: "Parque_Nacional_Marinho_dos_Abrolhos" },
  { id: 29, name: "Descobrimento", state: "BA", dist: 1050, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_do_Descobrimento" },
  { id: 30, name: "Alto Cariri", state: "BA", dist: 1058, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_do_Alto_Cariri" },
  { id: 31, name: "Monte Pascoal", state: "BA", dist: 1060, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_e_Hist\u00F3rico_do_Monte_Pascoal" },
  { id: 32, name: "Chapada dos Veadeiros", state: "GO", dist: 1060, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_da_Chapada_dos_Veadeiros" },
  { id: 33, name: "Serra da Bodoquena", state: "MS", dist: 1066, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_da_Serra_da_Bodoquena" },
  { id: 34, name: "Pau Brasil", state: "BA", dist: 1097, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_do_Pau-Brasil" },
  { id: 35, name: "Serra das Lontras", state: "BA", dist: 1205, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_da_Serra_das_Lontras" },
  { id: 36, name: "Boa Nova", state: "BA", dist: 1226, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_de_Boa_Nova" },
  { id: 37, name: "Pantanal Matogrossense", state: "MT", dist: 1302, access: "\u{1F697}\u26F5", status: "limitado", slug: "Parque_Nacional_do_Pantanal_Matogrossense" },
  { id: 38, name: "Chapada Diamantina", state: "BA", dist: 1310, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_da_Chapada_Diamantina" },
  { id: 39, name: "Chapada dos Guimar\u00E3es", state: "MT", dist: 1332, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_da_Chapada_dos_Guimar\u00E3es" },
  { id: 40, name: "Araguaia", state: "TO", dist: 1496, access: "\u{1F697}", status: "fechado", slug: "Parque_Nacional_do_Araguaia" },
  { id: 41, name: "Nascentes do Rio Parna\u00EDba", state: "BA/MA/PI/TO", dist: 1505, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_das_Nascentes_do_Rio_Parna\u00EDba" },
  { id: 42, name: "Boqueir\u00E3o da On\u00E7a", state: "BA", dist: 1584, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_do_Boqueir\u00E3o_da_On\u00E7a" },
  { id: 43, name: "Serra das Confus\u00F5es", state: "PI", dist: 1632, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_da_Serra_das_Confus\u00F5es" },
  { id: 44, name: "Serra de Itabaiana", state: "SE", dist: 1732, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_Serra_de_Itabaiana" },
  { id: 45, name: "Serra da Capivara", state: "PI", dist: 1744, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_Serra_da_Capivara" },
  { id: 46, name: "Chapada das Mesas", state: "MA", dist: 1816, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_da_Chapada_das_Mesas" },
  { id: 47, name: "Catimbau", state: "PE", dist: 1942, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_do_Catimbau" },
  { id: 48, name: "Campos Ferruginosos", state: "PA", dist: 1947, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_dos_Campos_Ferruginosos" },
  { id: 49, name: "Rio Novo", state: "PA", dist: 2037, access: "\u{1F697}\u26F5", status: "limitado", slug: "Parque_Nacional_do_Rio_Novo" },
  { id: 50, name: "Serra do Pardo", state: "PA", dist: 2122, access: "\u{1F697}\u26F5", status: "limitado", slug: "Parque_Nacional_da_Serra_do_Pardo" },
  { id: 51, name: "Juruena", state: "AM/MT", dist: 2204, access: "\u{1F697}\u26F5", status: "limitado", slug: "Parque_Nacional_do_Juruena" },
  { id: 52, name: "Jamanxim", state: "PA", dist: 2206, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_do_Jamanxim" },
  { id: 53, name: "Sete Cidades", state: "PI", dist: 2226, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_de_Sete_Cidades" },
  { id: 54, name: "Paca\u00E1s Novos", state: "RO", dist: 2243, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_de_Paca\u00E1s_Novos" },
  { id: 55, name: "Furna Feia", state: "RN", dist: 2277, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_da_Furna_Feia" },
  { id: 56, name: "Ubajara", state: "CE", dist: 2288, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_de_Ubajara" },
  { id: 57, name: "Serra da Cutia", state: "RO", dist: 2290, access: "\u{1F697}\u26F5", status: "limitado", slug: "Parque_Nacional_da_Serra_da_Cutia" },
  { id: 58, name: "Campos Amaz\u00F4nicos", state: "AM/RO", dist: 2322, access: "\u{1F697}\u26F5", status: "limitado", slug: "Parque_Nacional_dos_Campos_Amaz\u00F4nicos" },
  { id: 59, name: "Acari", state: "AM", dist: 2357, access: "\u26F5", status: "limitado", slug: "Parque_Nacional_do_Acari" },
  { id: 60, name: "Amaz\u00F4nia", state: "PA", dist: 2396, access: "\u{1F697}\u26F5", status: "aberto", slug: "Parque_Nacional_da_Amaz\u00F4nia" },
  { id: 61, name: "Jericoacoara", state: "CE", dist: 2402, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_de_Jericoacoara" },
  { id: 62, name: "Len\u00E7\u00F3is Maranhenses", state: "MA", dist: 2421, access: "\u{1F697}", status: "aberto", slug: "Parque_Nacional_dos_Len\u00E7\u00F3is_Maranhenses" },
  { id: 63, name: "Mapinguari", state: "AM/RO", dist: 2522, access: "\u2708\uFE0F\u26F5", status: "limitado", slug: "Parque_Nacional_Mapinguari" },
  { id: 64, name: "Nascentes do Lago Jari", state: "AM", dist: 2595, access: "\u2708\uFE0F\u26F5", status: "limitado", slug: "Parque_Nacional_das_Nascentes_do_Lago_Jari" },
  { id: 65, name: "Marinho de Fernando de Noronha", state: "PE", dist: 2669, access: "\u2708\uFE0F", status: "aberto", slug: "Parque_Nacional_Marinho_de_Fernando_de_Noronha" },
  { id: 66, name: "Anavilhanas", state: "AM", dist: 2810, access: "\u26F5", status: "aberto", slug: "Parque_Nacional_de_Anavilhanas" },
  { id: 67, name: "Ja\u00FA", state: "AM", dist: 2813, access: "\u26F5", status: "limitado", slug: "Parque_Nacional_do_Ja\u00FA" },
  { id: 68, name: "Montanhas do Tumucumaque", state: "AP", dist: 2906, access: "\u2708\uFE0F\u26F5", status: "limitado", slug: "Parque_Nacional_Montanhas_do_Tumucumaque" },
  { id: 69, name: "Cabo Orange", state: "AP", dist: 3056, access: "\u{1F697}\u26F5", status: "limitado", slug: "Parque_Nacional_do_Cabo_Orange" },
  { id: 70, name: "Viru\u00E1", state: "RR", dist: 3176, access: "\u{1F697}", status: "limitado", slug: "Parque_Nacional_do_Viru\u00E1" },
  { id: 71, name: "Serra da Mocidade", state: "RR", dist: 3204, access: "\u2708\uFE0F\u26F5", status: "limitado", slug: "Parque_Nacional_da_Serra_da_Mocidade" },
  { id: 72, name: "Serra do Divisor", state: "AC", dist: 3347, access: "\u{1F697}\u26F5", status: "limitado", slug: "Parque_Nacional_da_Serra_do_Divisor" },
  { id: 73, name: "Pico da Neblina", state: "AM", dist: 3423, access: "\u2708\uFE0F\u26F5", status: "fechado", slug: "Parque_Nacional_do_Pico_da_Neblina" },
  { id: 74, name: "Monte Roraima", state: "RR", dist: 3528, access: "\u{1F697}\u{1F97E}", status: "aberto", slug: "Parque_Nacional_do_Monte_Roraima" },
];
